version: '3'

services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: b-1.demo-cluster-1.yphti9.c21.kafka.us-east-1.amazonaws.com:9094,b-3.demo-cluster-1.yphti9.c21.kafka.us-east-1.amazonaws.com:9094,b-2.demo-cluster-1.yphti9.c21.kafka.us-east-1.amazonaws.com:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "AWSKafkaDemoTopic:1:3"
